CREATE TABLE IF NOT EXSISTS `website_data`.`Users`(
	`id` INT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(255) NOT NULL, 
	`username` VARCHAR(100) NOT NULL,
       	`password` VARCHAR(100) NOT NULL, 
	`created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	`modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	UNIQUE (`email`),
	UNIQUE (`username`)

);	
